/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

/**
 *
 * @author Naira Lohani
 */
import Controle.Minhafuncao;
import Modelo.FuncionarioDAO;
import static Visão.Crudfuncionario.jTable2;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class cadfuncionario extends javax.swing.JFrame {

    /**
     * Creates new form cadform
     */
    FuncionarioDAO funcio = new FuncionarioDAO();
    public cadfuncionario() {
        initComponents();
        this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtxt_email_funcionario = new javax.swing.JTextField();
        jButtoncancel = new javax.swing.JButton();
        jButtoncadfunc = new javax.swing.JButton();
        jtxt_nome_funcionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxt_telefone_funcionario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordFuncionario = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jtxt_cpf_funcionario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelclose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelmn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 248, 225));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("E-MAIL:");

        jtxt_email_funcionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_email_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_email_funcionarioActionPerformed(evt);
            }
        });

        jButtoncancel.setBackground(new java.awt.Color(211, 47, 47));
        jButtoncancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtoncancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtoncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_cancel_48_10277.png"))); // NOI18N
        jButtoncancel.setText("Cancelar");
        jButtoncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelActionPerformed(evt);
            }
        });

        jButtoncadfunc.setBackground(new java.awt.Color(211, 47, 47));
        jButtoncadfunc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtoncadfunc.setForeground(new java.awt.Color(255, 255, 255));
        jButtoncadfunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_sign-add_299068 (1).png"))); // NOI18N
        jButtoncadfunc.setText("Cadastrar");
        jButtoncadfunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncadfuncActionPerformed(evt);
            }
        });

        jtxt_nome_funcionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_nome_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nome_funcionarioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("NOME:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("SENHA:");

        jtxt_telefone_funcionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_telefone_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_telefone_funcionarioActionPerformed(evt);
            }
        });
        jtxt_telefone_funcionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_telefone_funcionarioKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("TELEFONE:");

        jPasswordFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFuncionarioActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("CPF:");

        jtxt_cpf_funcionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_cpf_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_cpf_funcionarioActionPerformed(evt);
            }
        });
        jtxt_cpf_funcionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_cpf_funcionarioKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButtoncancel)
                        .addGap(18, 18, 18)
                        .addComponent(jButtoncadfunc, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_cpf_funcionario))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_telefone_funcionario))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPasswordFuncionario))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxt_email_funcionario)
                                    .addComponent(jtxt_nome_funcionario))))))
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_nome_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxt_email_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jPasswordFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jtxt_telefone_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jtxt_cpf_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoncadfunc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtoncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        jPanel1.setBackground(new java.awt.Color(211, 47, 47));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelclose.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabelclose.setForeground(new java.awt.Color(248, 242, 224));
        jLabelclose.setText("X");
        jLabelclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcloseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 242, 224));
        jLabel2.setText("CADASTRAR FUNCIONÁRIO");

        jLabelmn.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabelmn.setForeground(new java.awt.Color(248, 242, 224));
        jLabelmn.setText("-");
        jLabelmn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelmn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelmnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(84, 84, 84)
                .addComponent(jLabelmn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelclose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelmn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcloseMouseClicked
         this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelcloseMouseClicked

    private void jLabelmnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmnMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelmnMouseClicked

    private void jtxt_email_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_email_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_email_funcionarioActionPerformed

    private void jButtoncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtoncancelActionPerformed

    public boolean verificText(){
        if(jtxt_nome_funcionario.getText().equals("")|| jPasswordFuncionario.getPassword().equals("")|| jtxt_telefone_funcionario.getText().equals("") ||  jtxt_email_funcionario.getText().equals("")|| jtxt_cpf_funcionario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Um ou mais espaços vazios!");
            return false;
        }
        else{
                return true;
        }
        
        
    }
    
    private void jButtoncadfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncadfuncActionPerformed
        String nome = jtxt_nome_funcionario.getText();
        String email = jtxt_email_funcionario.getText();
        String senha = new String(jPasswordFuncionario.getPassword());
        String telefone = jtxt_telefone_funcionario.getText();
        String cpf =jtxt_cpf_funcionario.getText();
        if(verificText()){
          FuncionarioDAO fciona = new FuncionarioDAO();
        fciona.InserirAtualizarDeletarFuncionario('i', null, nome, email,senha, telefone, cpf);
    Principal.lblqtd_funcionários.setText("Quantidade de Funcionários = "+ Integer.toString(Minhafuncao.contarDados("funcionario")));
     Crudfuncionario.jTable2.setModel(new DefaultTableModel(null, new Object[]{"Id","Nome","E-mail","Senha","Telefone","Cpf"}));   
   funcio.peencherTabelaFuncionário(Crudfuncionario.jTable2, "");
        }
    }//GEN-LAST:event_jButtoncadfuncActionPerformed

    private void jtxt_nome_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nome_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nome_funcionarioActionPerformed

    private void jtxt_telefone_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_telefone_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_telefone_funcionarioActionPerformed

    private void jtxt_telefone_funcionarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_telefone_funcionarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_telefone_funcionarioKeyTyped

    private void jtxt_cpf_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_cpf_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_cpf_funcionarioActionPerformed

    private void jtxt_cpf_funcionarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_cpf_funcionarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_cpf_funcionarioKeyTyped

    private void jPasswordFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadfuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncadfunc;
    private javax.swing.JButton jButtoncancel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelclose;
    private javax.swing.JLabel jLabelmn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFuncionario;
    private javax.swing.JTextField jtxt_cpf_funcionario;
    private javax.swing.JTextField jtxt_email_funcionario;
    private javax.swing.JTextField jtxt_nome_funcionario;
    private javax.swing.JTextField jtxt_telefone_funcionario;
    // End of variables declaration//GEN-END:variables
}
