/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import Controle.Minhafuncao;
import Modelo.ClienteDAO;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Naira Lohani
 */
public class Crudcliente extends javax.swing.JFrame {

    /**
     * Creates new form Crudcliente
     */
    ClienteDAO cli = new ClienteDAO();
    DefaultTableModel model;
    public Crudcliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        cli.peencherTabelaCliente(jTable1, "");
        model =(DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelclose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelmn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxt_email = new javax.swing.JTextField();
        jButtondelete_cliente = new javax.swing.JButton();
        jButtonaddcliente = new javax.swing.JButton();
        jtxt_nome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_end = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jtxt_telefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxt_id_cliente = new javax.swing.JTextField();
        jButton_edit_cliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxt_search_cliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(211, 47, 47));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelclose.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabelclose.setForeground(new java.awt.Color(248, 242, 224));
        jLabelclose.setText("X");
        jLabelclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcloseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 242, 224));
        jLabel2.setText("ADMINISTRAR CLIENTES");

        jLabelmn.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabelmn.setForeground(new java.awt.Color(248, 242, 224));
        jLabelmn.setText("-");
        jLabelmn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelmn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelmnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelmn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelclose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelmn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 248, 225));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("ENDEREÇO:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("E-MAIL:");

        jtxt_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_emailActionPerformed(evt);
            }
        });

        jButtondelete_cliente.setBackground(new java.awt.Color(211, 47, 47));
        jButtondelete_cliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtondelete_cliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtondelete_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_cancel_48_10277.png"))); // NOI18N
        jButtondelete_cliente.setText("Deletar");
        jButtondelete_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondelete_clienteActionPerformed(evt);
            }
        });

        jButtonaddcliente.setBackground(new java.awt.Color(211, 47, 47));
        jButtonaddcliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonaddcliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonaddcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_sign-add_299068 (1).png"))); // NOI18N
        jButtonaddcliente.setText("Adicionar");
        jButtonaddcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddclienteActionPerformed(evt);
            }
        });

        jtxt_nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nomeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("NOME:");

        jTextArea_end.setColumns(20);
        jTextArea_end.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea_end.setRows(5);
        jScrollPane1.setViewportView(jTextArea_end);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("TELEFONE:");

        jtxt_telefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_telefoneActionPerformed(evt);
            }
        });
        jtxt_telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_telefoneKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("ID:");

        jtxt_id_cliente.setEditable(false);
        jtxt_id_cliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_id_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_id_clienteActionPerformed(evt);
            }
        });

        jButton_edit_cliente.setBackground(new java.awt.Color(211, 47, 47));
        jButton_edit_cliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_edit_cliente.setForeground(new java.awt.Color(255, 255, 255));
        jButton_edit_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_compose_1055085.png"))); // NOI18N
        jButton_edit_cliente.setText("Editar");
        jButton_edit_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_edit_clienteActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(240, 240, 240));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "E-MAIL", "TELEFONE", "ENDEREÇO"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jtxt_search_cliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_search_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_search_clienteActionPerformed(evt);
            }
        });
        jtxt_search_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_search_clienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxt_search_clienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_search_clienteKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("DIGITE UM VALOR PARA PESQUISAR:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addGap(381, 381, 381))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButtondelete_cliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_edit_cliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonaddcliente))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtxt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxt_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_search_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(258, 258, 258))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_search_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtxt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtondelete_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_edit_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonaddcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcloseMouseClicked
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelcloseMouseClicked

    private void jLabelmnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmnMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelmnMouseClicked

    private void jtxt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_emailActionPerformed

    private void jButtondelete_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondelete_clienteActionPerformed
        // TODO add your handling code here:
        if(jtxt_id_cliente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nenhum Cliente Selecionado!");
        }else{
            int id =Integer.valueOf(jtxt_id_cliente.getText());
        cli.InserirAtualizarDeletarCliente('d', id, null, null, null, null);
        cli.peencherTabelaCliente(jTable1, "");
         jTable1.setModel(new DefaultTableModel(null, new Object[]{"Id","Nome","E-mail","Telefone","Endereço"}));
       cli.peencherTabelaCliente(Crudcliente.jTable1, "");
        
        Principal.lblqtd_clientes.setText("Quantidade de Clientes = "+ Integer.toString(Minhafuncao.contarDados("cliente")));
        
        jtxt_id_cliente.setText("");
        jtxt_nome.setText("");
        jtxt_email.setText("");
        jtxt_telefone.setText("");
        jTextArea_end.setText("");
        }
        
        
    }//GEN-LAST:event_jButtondelete_clienteActionPerformed

    private void jButtonaddclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddclienteActionPerformed
        

cadform cdf1 = new cadform();
        cdf1.setVisible(true);
        cdf1.pack();
        cdf1.setLocationRelativeTo(null);
        cdf1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jButtonaddclienteActionPerformed

    private void jtxt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nomeActionPerformed

    private void jtxt_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_telefoneActionPerformed

    private void jtxt_telefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_telefoneKeyTyped
        // permite apenas números:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtxt_telefoneKeyTyped

    private void jtxt_id_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_id_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_id_clienteActionPerformed

    public boolean verificText(){
        if(jtxt_nome.getText().equals("")|| jtxt_id_cliente.getText().equals("") || jtxt_email.getText().equals("")|| jtxt_telefone.getText().equals("") || jTextArea_end.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Um ou mais espaços vazios!");
            return false;
        }
        else{
                return true;
        }
        
        
    }
    
    private void jButton_edit_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_edit_clienteActionPerformed

        String nome = jtxt_nome.getText();
        String email = jtxt_email.getText();
        String telefone = jtxt_telefone.getText();
        String endereco = jTextArea_end.getText();
        int id =Integer.valueOf(jtxt_id_cliente.getText());
        
        if(verificText()){
            ClienteDAO cli = new ClienteDAO();
            cli.InserirAtualizarDeletarCliente('u', id, nome, email, telefone, endereco);
            jTable1.setModel(new DefaultTableModel(null, new Object[]{"Id","Nome","E-mail","Telefone","Endereço"}));
       cli.peencherTabelaCliente(Crudcliente.jTable1, "");
            //Principal.lblqtd_clientes.setText("Quantidade de Clientes = "+ Integer.toString(Minhafuncao.contarDados("cliente")));
        }
        
    }//GEN-LAST:event_jButton_edit_clienteActionPerformed
int rowIndex;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        rowIndex = jTable1.getSelectedRow();
        
        
        jtxt_id_cliente.setText(model.getValueAt(rowIndex, 0).toString());
        jtxt_nome.setText(model.getValueAt(rowIndex, 1).toString());
        jtxt_email.setText(model.getValueAt(rowIndex, 2).toString());
        jtxt_telefone.setText(model.getValueAt(rowIndex, 3).toString());
        jTextArea_end.setText(model.getValueAt(rowIndex, 4).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jtxt_search_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_search_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_search_clienteActionPerformed

    private void jtxt_search_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_search_clienteKeyTyped
       
    }//GEN-LAST:event_jtxt_search_clienteKeyTyped

    private void jtxt_search_clienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_search_clienteKeyPressed
    
    }//GEN-LAST:event_jtxt_search_clienteKeyPressed

    private void jtxt_search_clienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_search_clienteKeyReleased
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"Id","Nome","E-mail","Telefone","Endereço"}));
        cli.peencherTabelaCliente(jTable1, jtxt_search_cliente.getText()); 
    }//GEN-LAST:event_jtxt_search_clienteKeyReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN){
            rowIndex = jTable1.getSelectedRow();
             jtxt_id_cliente.setText(model.getValueAt(rowIndex, 0).toString());
        jtxt_nome.setText(model.getValueAt(rowIndex, 1).toString());
        jtxt_email.setText(model.getValueAt(rowIndex, 2).toString());
        jtxt_telefone.setText(model.getValueAt(rowIndex, 3).toString());
        jTextArea_end.setText(model.getValueAt(rowIndex, 4).toString());
        }
        
    }//GEN-LAST:event_jTable1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crudcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crudcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crudcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crudcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crudcliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_edit_cliente;
    private javax.swing.JButton jButtonaddcliente;
    private javax.swing.JButton jButtondelete_cliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelclose;
    private javax.swing.JLabel jLabelmn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_end;
    private javax.swing.JTextField jtxt_email;
    private javax.swing.JTextField jtxt_id_cliente;
    private javax.swing.JTextField jtxt_nome;
    private javax.swing.JTextField jtxt_search_cliente;
    private javax.swing.JTextField jtxt_telefone;
    // End of variables declaration//GEN-END:variables
}
