/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import Controle.Minhafuncao;
import Modelo.FuncionarioDAO;
import Modelo.GerenteDAO;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Naira Lohani
 */
public class CrudGerente extends javax.swing.JFrame {

    /**
     * Creates new form Crudcliente
     */
    GerenteDAO ger = new GerenteDAO();
    DefaultTableModel model;
    public CrudGerente() {
        initComponents();
        this.setLocationRelativeTo(null);
        ger.peencherTabelaGerente(jTable3, "");
        model =(DefaultTableModel) jTable3.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelclose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelmn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtxt_email_gerente = new javax.swing.JTextField();
        jButtondelete_gerente = new javax.swing.JButton();
        jButtonaddgerente = new javax.swing.JButton();
        jtxt_nome_gerente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxt_telefone_gerente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxt_id_gerente = new javax.swing.JTextField();
        jButton_edit_gerente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jtxt_search_gerente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPasswordGerente = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jtxt_cpf_gerente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(211, 47, 47));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelclose.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabelclose.setForeground(new java.awt.Color(248, 242, 224));
        jLabelclose.setText("X");
        jLabelclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcloseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 242, 224));
        jLabel2.setText("ADMINISTRAR FUNCIONÁRIOS");

        jLabelmn.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabelmn.setForeground(new java.awt.Color(248, 242, 224));
        jLabelmn.setText("-");
        jLabelmn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelmn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelmnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelmn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelclose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelmn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 248, 225));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("E-MAIL:");

        jtxt_email_gerente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_email_gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_email_gerenteActionPerformed(evt);
            }
        });

        jButtondelete_gerente.setBackground(new java.awt.Color(211, 47, 47));
        jButtondelete_gerente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtondelete_gerente.setForeground(new java.awt.Color(255, 255, 255));
        jButtondelete_gerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_cancel_48_10277.png"))); // NOI18N
        jButtondelete_gerente.setText("Deletar");
        jButtondelete_gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondelete_gerenteActionPerformed(evt);
            }
        });

        jButtonaddgerente.setBackground(new java.awt.Color(211, 47, 47));
        jButtonaddgerente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonaddgerente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonaddgerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_sign-add_299068 (1).png"))); // NOI18N
        jButtonaddgerente.setText("Adicionar");
        jButtonaddgerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddgerenteActionPerformed(evt);
            }
        });

        jtxt_nome_gerente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_nome_gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nome_gerenteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("NOME:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("TELEFONE:");

        jtxt_telefone_gerente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_telefone_gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_telefone_gerenteActionPerformed(evt);
            }
        });
        jtxt_telefone_gerente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_telefone_gerenteKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("ID:");

        jtxt_id_gerente.setEditable(false);
        jtxt_id_gerente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_id_gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_id_gerenteActionPerformed(evt);
            }
        });

        jButton_edit_gerente.setBackground(new java.awt.Color(211, 47, 47));
        jButton_edit_gerente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_edit_gerente.setForeground(new java.awt.Color(255, 255, 255));
        jButton_edit_gerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_compose_1055085.png"))); // NOI18N
        jButton_edit_gerente.setText("Editar");
        jButton_edit_gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_edit_gerenteActionPerformed(evt);
            }
        });

        jTable3.setBackground(new java.awt.Color(240, 240, 240));
        jTable3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "E-MAIL", "SENHA", "TELEFONE", "CPF"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jTable3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable3KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable3);

        jtxt_search_gerente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_search_gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_search_gerenteActionPerformed(evt);
            }
        });
        jtxt_search_gerente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_search_gerenteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxt_search_gerenteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_search_gerenteKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("DIGITE UM VALOR PARA PESQUISAR:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("SENHA:");

        jPasswordGerente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordGerenteActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("CPF:");

        jtxt_cpf_gerente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_cpf_gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_cpf_gerenteActionPerformed(evt);
            }
        });
        jtxt_cpf_gerente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_cpf_gerenteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel8))
                                            .addGap(381, 381, 381))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtxt_telefone_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtondelete_gerente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_edit_gerente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonaddgerente))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtxt_email_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jtxt_nome_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxt_id_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_cpf_gerente))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPasswordGerente)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_search_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(258, 258, 258))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_search_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_id_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_nome_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_email_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtxt_telefone_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jtxt_cpf_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtondelete_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_edit_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonaddgerente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1176, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcloseMouseClicked
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelcloseMouseClicked

    private void jLabelmnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmnMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelmnMouseClicked

    private void jtxt_email_gerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_email_gerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_email_gerenteActionPerformed

    private void jButtondelete_gerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondelete_gerenteActionPerformed
        // TODO add your handling code here:
        if(jtxt_id_gerente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nenhum Cliente Selecionado!");
        }else{
            int id =Integer.valueOf(jtxt_id_gerente.getText());
        ger.InserirAtualizarDeletarGerente('d', id, null, null, null, null,null);
       ger.peencherTabelaGerente(jTable3, "");
         jTable3.setModel(new DefaultTableModel(null, new Object[]{"Id","Nome","E-mail","Senha","Telefone","Cpf"}));
       ger.peencherTabelaGerente(CrudGerente.jTable3, "");
        
        Principal.lblqtd_gerentes.setText("Quantidade de Gerentes = "+ Integer.toString(Minhafuncao.contarDados("gerente")));
        
        jtxt_id_gerente.setText("");
        jtxt_nome_gerente.setText("");
        jtxt_email_gerente.setText("");
        jPasswordGerente.setText("");
        jtxt_telefone_gerente.setText("");
        jtxt_cpf_gerente.setText("");
        
        }
        
        
    }//GEN-LAST:event_jButtondelete_gerenteActionPerformed

    private void jButtonaddgerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddgerenteActionPerformed
        

//cadfuncionario cdfunc = new cadfuncionario();
//        cdfunc.setVisible(true);
//        cdfunc.pack();
//        cdfunc.setLocationRelativeTo(null);
//        cdfunc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jButtonaddgerenteActionPerformed

    private void jtxt_nome_gerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nome_gerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nome_gerenteActionPerformed

    private void jtxt_telefone_gerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_telefone_gerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_telefone_gerenteActionPerformed

    private void jtxt_telefone_gerenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_telefone_gerenteKeyTyped
        // permite apenas números:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtxt_telefone_gerenteKeyTyped

    private void jtxt_id_gerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_id_gerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_id_gerenteActionPerformed

     public boolean verificText(){
        if(jtxt_nome_gerente.getText().equals("") || jtxt_email_gerente.getText().equals("")|| jtxt_cpf_gerente.getText().equals("")||jtxt_cpf_gerente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Um ou mais espaços vazios!");
            return false;
        }
        else{
                return true;
        }
        
        
    }
    
    private void jButton_edit_gerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_edit_gerenteActionPerformed

       String nome = jtxt_nome_gerente.getText();
        String email = jtxt_email_gerente.getText();
        String senha = new String(jPasswordGerente.getPassword());
        String telefone = jtxt_telefone_gerente.getText();
        String cpf =jtxt_cpf_gerente.getText();
        int id =Integer.valueOf(jtxt_id_gerente.getText());
        
        if(verificText()){
            FuncionarioDAO func= new FuncionarioDAO();
            func.InserirAtualizarDeletarFuncionario('u', id, nome, email,senha, telefone, cpf);
            jTable3.setModel(new DefaultTableModel(null, new Object[]{"Id","Nome","E-mail","Senha","Telefone","Cpf"}));
       func.peencherTabelaFuncionário(CrudGerente.jTable3, "");
          
        }
        
    }//GEN-LAST:event_jButton_edit_gerenteActionPerformed
int rowIndex;
    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        rowIndex = jTable3.getSelectedRow();
        
        
     jtxt_id_gerente.setText(model.getValueAt(rowIndex, 0).toString());
        jtxt_nome_gerente.setText(model.getValueAt(rowIndex, 1).toString());
        jtxt_email_gerente.setText(model.getValueAt(rowIndex, 2).toString());
        jPasswordGerente.setText(model.getValueAt(rowIndex, 3).toString());
        jtxt_telefone_gerente.setText(model.getValueAt(rowIndex, 4).toString());
        jtxt_cpf_gerente.setText(model.getValueAt(rowIndex, 5).toString());
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void jtxt_search_gerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_search_gerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_search_gerenteActionPerformed

    private void jtxt_search_gerenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_search_gerenteKeyTyped
       
    }//GEN-LAST:event_jtxt_search_gerenteKeyTyped

    private void jtxt_search_gerenteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_search_gerenteKeyPressed
    
    }//GEN-LAST:event_jtxt_search_gerenteKeyPressed

    private void jtxt_search_gerenteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_search_gerenteKeyReleased
        jTable3.setModel(new DefaultTableModel(null, new Object[]{"Id","Nome","E-mail","Senha","Telefone","Cpf"}));
        func.peencherTabelaFuncionário(jTable3, jtxt_search_gerente.getText()); 
    }//GEN-LAST:event_jtxt_search_gerenteKeyReleased

    private void jTable3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN){
            rowIndex = jTable3.getSelectedRow();
             jtxt_id_gerente.setText(model.getValueAt(rowIndex, 0).toString());
        jtxt_nome_gerente.setText(model.getValueAt(rowIndex, 1).toString());
        jtxt_email_gerente.setText(model.getValueAt(rowIndex, 2).toString());
        jPasswordGerente.setText(model.getValueAt(rowIndex, 3).toString());
        jtxt_telefone_gerente.setText(model.getValueAt(rowIndex, 4).toString());
        jtxt_cpf_gerente.setText(model.getValueAt(rowIndex, 5).toString());
        }
        
    }//GEN-LAST:event_jTable3KeyReleased

    private void jtxt_cpf_gerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_cpf_gerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_cpf_gerenteActionPerformed

    private void jtxt_cpf_gerenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_cpf_gerenteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_cpf_gerenteKeyTyped

    private void jPasswordGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordGerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_edit_gerente;
    private javax.swing.JButton jButtonaddgerente;
    private javax.swing.JButton jButtondelete_gerente;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelclose;
    private javax.swing.JLabel jLabelmn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordGerente;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable3;
    private javax.swing.JTextField jtxt_cpf_gerente;
    private javax.swing.JTextField jtxt_email_gerente;
    private javax.swing.JTextField jtxt_id_gerente;
    private javax.swing.JTextField jtxt_nome_gerente;
    private javax.swing.JTextField jtxt_search_gerente;
    private javax.swing.JTextField jtxt_telefone_gerente;
    // End of variables declaration//GEN-END:variables
}
