/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import Controle.Minhafuncao;
import Modelo.FuncionarioDAO;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Naira Lohani
 */
public class Crudfuncionario extends javax.swing.JFrame {

    /**
     * Creates new form Crudcliente
     */
    FuncionarioDAO func = new FuncionarioDAO();
    DefaultTableModel model;
    public Crudfuncionario() {
        initComponents();
        this.setLocationRelativeTo(null);
        func.peencherTabelaFuncionário(jTable2, "");
        model =(DefaultTableModel) jTable2.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelclose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelmn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtxt_email_funcionario = new javax.swing.JTextField();
        jButtondelete_funcionario = new javax.swing.JButton();
        jButtonaddfuncionario = new javax.swing.JButton();
        jtxt_nome_funcionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxt_telefone_funcionario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxt_id_funcionario = new javax.swing.JTextField();
        jButton_edit_funcionario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jtxt_search_funcionario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPasswordFuncionario = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jtxt_cpf_funcionario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(211, 47, 47));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelclose.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabelclose.setForeground(new java.awt.Color(248, 242, 224));
        jLabelclose.setText("X");
        jLabelclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcloseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 242, 224));
        jLabel2.setText("ADMINISTRAR FUNCIONÁRIOS");

        jLabelmn.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabelmn.setForeground(new java.awt.Color(248, 242, 224));
        jLabelmn.setText("-");
        jLabelmn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelmn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelmnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelmn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelclose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelmn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 248, 225));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("E-MAIL:");

        jtxt_email_funcionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_email_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_email_funcionarioActionPerformed(evt);
            }
        });

        jButtondelete_funcionario.setBackground(new java.awt.Color(211, 47, 47));
        jButtondelete_funcionario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtondelete_funcionario.setForeground(new java.awt.Color(255, 255, 255));
        jButtondelete_funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_cancel_48_10277.png"))); // NOI18N
        jButtondelete_funcionario.setText("Deletar");
        jButtondelete_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondelete_funcionarioActionPerformed(evt);
            }
        });

        jButtonaddfuncionario.setBackground(new java.awt.Color(211, 47, 47));
        jButtonaddfuncionario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonaddfuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jButtonaddfuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_sign-add_299068 (1).png"))); // NOI18N
        jButtonaddfuncionario.setText("Adicionar");
        jButtonaddfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddfuncionarioActionPerformed(evt);
            }
        });

        jtxt_nome_funcionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_nome_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nome_funcionarioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("NOME:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("TELEFONE:");

        jtxt_telefone_funcionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_telefone_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_telefone_funcionarioActionPerformed(evt);
            }
        });
        jtxt_telefone_funcionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_telefone_funcionarioKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("ID:");

        jtxt_id_funcionario.setEditable(false);
        jtxt_id_funcionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_id_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_id_funcionarioActionPerformed(evt);
            }
        });

        jButton_edit_funcionario.setBackground(new java.awt.Color(211, 47, 47));
        jButton_edit_funcionario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_edit_funcionario.setForeground(new java.awt.Color(255, 255, 255));
        jButton_edit_funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfinder_compose_1055085.png"))); // NOI18N
        jButton_edit_funcionario.setText("Editar");
        jButton_edit_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_edit_funcionarioActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(240, 240, 240));
        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "E-MAIL", "SENHA", "TELEFONE", "CPF"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable2KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jtxt_search_funcionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_search_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_search_funcionarioActionPerformed(evt);
            }
        });
        jtxt_search_funcionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_search_funcionarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxt_search_funcionarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_search_funcionarioKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("DIGITE UM VALOR PARA PESQUISAR:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("SENHA:");

        jPasswordFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFuncionarioActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("CPF:");

        jtxt_cpf_funcionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxt_cpf_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_cpf_funcionarioActionPerformed(evt);
            }
        });
        jtxt_cpf_funcionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_cpf_funcionarioKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel8))
                                            .addGap(381, 381, 381))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtxt_telefone_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtondelete_funcionario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_edit_funcionario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonaddfuncionario))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtxt_email_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jtxt_nome_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxt_id_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_cpf_funcionario))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPasswordFuncionario)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_search_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(258, 258, 258))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_search_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_id_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_nome_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_email_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtxt_telefone_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jtxt_cpf_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtondelete_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_edit_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonaddfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1176, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcloseMouseClicked
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelcloseMouseClicked

    private void jLabelmnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmnMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelmnMouseClicked

    private void jtxt_email_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_email_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_email_funcionarioActionPerformed

    private void jButtondelete_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondelete_funcionarioActionPerformed
        // TODO add your handling code here:
        if(jtxt_id_funcionario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nenhum Cliente Selecionado!");
        }else{
            int id =Integer.valueOf(jtxt_id_funcionario.getText());
        func.InserirAtualizarDeletarFuncionario('d', id, null, null, null, null,null);
       func.peencherTabelaFuncionário(jTable2, "");
         jTable2.setModel(new DefaultTableModel(null, new Object[]{"Id","Nome","E-mail","Senha","Telefone","Cpf"}));
       func.peencherTabelaFuncionário(Crudfuncionario.jTable2, "");
        
        Principal.lblqtd_funcionários.setText("Quantidade de Funcionários = "+ Integer.toString(Minhafuncao.contarDados("funcionario")));
        
        jtxt_id_funcionario.setText("");
        jtxt_nome_funcionario.setText("");
        jtxt_email_funcionario.setText("");
        jPasswordFuncionario.setText("");
        jtxt_telefone_funcionario.setText("");
        jtxt_cpf_funcionario.setText("");
        
        }
        
        
    }//GEN-LAST:event_jButtondelete_funcionarioActionPerformed

    private void jButtonaddfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddfuncionarioActionPerformed
        

cadfuncionario cdfunc = new cadfuncionario();
        cdfunc.setVisible(true);
        cdfunc.pack();
        cdfunc.setLocationRelativeTo(null);
        cdfunc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jButtonaddfuncionarioActionPerformed

    private void jtxt_nome_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nome_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nome_funcionarioActionPerformed

    private void jtxt_telefone_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_telefone_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_telefone_funcionarioActionPerformed

    private void jtxt_telefone_funcionarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_telefone_funcionarioKeyTyped
        // permite apenas números:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtxt_telefone_funcionarioKeyTyped

    private void jtxt_id_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_id_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_id_funcionarioActionPerformed

     public boolean verificText(){
        if(jtxt_nome_funcionario.getText().equals("")|| jPasswordFuncionario.getPassword().equals("")|| jtxt_telefone_funcionario.getText().equals("")|| jtxt_id_funcionario.getText().equals("") || jtxt_email_funcionario.getText().equals("")|| jtxt_cpf_funcionario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Um ou mais espaços vazios!");
            return false;
        }
        else{
                return true;
        }
        
        
    }
    
    private void jButton_edit_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_edit_funcionarioActionPerformed

       String nome = jtxt_nome_funcionario.getText();
        String email = jtxt_email_funcionario.getText();
        String senha = new String(jPasswordFuncionario.getPassword());
        String telefone = jtxt_telefone_funcionario.getText();
        String cpf =jtxt_cpf_funcionario.getText();
        int id =Integer.valueOf(jtxt_id_funcionario.getText());
        
        if(verificText()){
            FuncionarioDAO func= new FuncionarioDAO();
            func.InserirAtualizarDeletarFuncionario('u', id, nome, email,senha, telefone, cpf);
            jTable2.setModel(new DefaultTableModel(null, new Object[]{"Id","Nome","E-mail","Senha","Telefone","Cpf"}));
       func.peencherTabelaFuncionário(Crudfuncionario.jTable2, "");
          
        }
        
    }//GEN-LAST:event_jButton_edit_funcionarioActionPerformed
int rowIndex;
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        rowIndex = jTable2.getSelectedRow();
        
        
     jtxt_id_funcionario.setText(model.getValueAt(rowIndex, 0).toString());
        jtxt_nome_funcionario.setText(model.getValueAt(rowIndex, 1).toString());
        jtxt_email_funcionario.setText(model.getValueAt(rowIndex, 2).toString());
        jPasswordFuncionario.setText(model.getValueAt(rowIndex, 3).toString());
        jtxt_telefone_funcionario.setText(model.getValueAt(rowIndex, 4).toString());
        jtxt_cpf_funcionario.setText(model.getValueAt(rowIndex, 5).toString());
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jtxt_search_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_search_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_search_funcionarioActionPerformed

    private void jtxt_search_funcionarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_search_funcionarioKeyTyped
       
    }//GEN-LAST:event_jtxt_search_funcionarioKeyTyped

    private void jtxt_search_funcionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_search_funcionarioKeyPressed
    
    }//GEN-LAST:event_jtxt_search_funcionarioKeyPressed

    private void jtxt_search_funcionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_search_funcionarioKeyReleased
        jTable2.setModel(new DefaultTableModel(null, new Object[]{"Id","Nome","E-mail","Senha","Telefone","Cpf"}));
        func.peencherTabelaFuncionário(jTable2, jtxt_search_funcionario.getText()); 
    }//GEN-LAST:event_jtxt_search_funcionarioKeyReleased

    private void jTable2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN){
            rowIndex = jTable2.getSelectedRow();
             jtxt_id_funcionario.setText(model.getValueAt(rowIndex, 0).toString());
        jtxt_nome_funcionario.setText(model.getValueAt(rowIndex, 1).toString());
        jtxt_email_funcionario.setText(model.getValueAt(rowIndex, 2).toString());
        jPasswordFuncionario.setText(model.getValueAt(rowIndex, 3).toString());
        jtxt_telefone_funcionario.setText(model.getValueAt(rowIndex, 4).toString());
        jtxt_cpf_funcionario.setText(model.getValueAt(rowIndex, 5).toString());
        }
        
    }//GEN-LAST:event_jTable2KeyReleased

    private void jtxt_cpf_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_cpf_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_cpf_funcionarioActionPerformed

    private void jtxt_cpf_funcionarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_cpf_funcionarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_cpf_funcionarioKeyTyped

    private void jPasswordFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crudfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crudfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crudfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crudfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crudfuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_edit_funcionario;
    private javax.swing.JButton jButtonaddfuncionario;
    private javax.swing.JButton jButtondelete_funcionario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelclose;
    private javax.swing.JLabel jLabelmn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFuncionario;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable2;
    private javax.swing.JTextField jtxt_cpf_funcionario;
    private javax.swing.JTextField jtxt_email_funcionario;
    private javax.swing.JTextField jtxt_id_funcionario;
    private javax.swing.JTextField jtxt_nome_funcionario;
    private javax.swing.JTextField jtxt_search_funcionario;
    private javax.swing.JTextField jtxt_telefone_funcionario;
    // End of variables declaration//GEN-END:variables
}
